version: '3.8'

services:
  ftps-server:
    image: alwisnhe/ftpsserver
    container_name: alwisnhe/ftpsserver
    network_mode: "host"
    environment:
      - FTPS_CERTFILE=/app/cert/ftps_local.crt
      - FTPS_KEYFILE=/app/cert/ftps_local.key
      - FTPS_ENDERECO=0.0.0.0
      - FTPS_PORTA=2121
      - FTPS_USUARIO=usuario
      - FTPS_SENHA=usuario@123
      - FTPS_DIRETORIO=/app/ftp/
    volumes:
      - ./cert:/app/cert
      - ./data:/app/ftp
networks:
  ftps_network:
    driver: bridge
