version: '3.8'

services:
  ftps-server:
    image: alwisnhe/ftpsserver
    container_name: alwisnhe/ftpsserver
    # network_mode: "host"
    ports:
      - "2121:2121"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTPS_CERTFILE=/app/cert/ftps_local.crt
      - FTPS_KEYFILE=/app/cert/ftps_local.key
      - FTPS_ENDERECO=0.0.0.0
      - FTPS_PORTA=21
      - FTPS_USUARIO=guest
      - FTPS_SENHA=guest
      - FTPS_DIRETORIO=/app/ftp/
      - FTPS_MINPORTA=21100
      - FTPS_MAXPORTA=21110
    volumes:
      - ./cert:/app/cert
      - ./data:/app/ftp
